version: "3"

services:
  cliapp:
    image: cliapp
    build: ./Dockerfile.cliapp
    volumes: 
      - type: volume
        source: shared-volume
        target: /opt/chimera/data

  webapp:
    image: webapp
    build: ./Dockerfile.webapp
    volumes: 
      - type: volume
        source: shared-volume
        target: /opt/chimera/data
    ports:
      - 5000:80

volumes:
  shared-volume:
  